### PR TITLE
fix(tui): project hidden peer receipts on first sidebar reveal

### PR DESCRIPTION
**Pull request by damianvtran**
## What and why

**C2 — a peer `lop send` received while a session is hidden never paints on the first sidebar reveal / warm swap.** The inbound `PeerMessageBlock` is missing until a second reload. The operator sees an empty transcript on resume even though the receipt already landed; a later reload suddenly shows it.

### Root cause

`PeerMessageDeliveredEvent` is a settled durable row with no `_MESSAGE_PHASE` lifecycle (that machinery orders streaming beats of a turn; a phase rank is a category error for one settled append). `_remember_live` never recorded it in the viewer's `_live_history`.

Two freshness signals then stay still:

1. `history_generation` only bumps on compaction / prune, so a plain peer append never invalidates the display window.
2. `history_message_count` never grows, so `_sidebar_presentation_current`'s count guard reuses the stale cached presentation, and `_commit_sidebar_session`'s `total > incoming.history_size` delta never fires.

The inbound row is therefore never projected until a full reload rebuilds the window from disk.

### The fix

`_remember_live` now records the settled row keyed by the **persisted** `message_id` (and seeds `_durable_seed_ids` so the next sync treats it as durable rather than re-painting it). That grows the count by exactly one, which is what makes both freshness signals move. Painting stays with the existing replay / delta paths and their `_live_peer_receipts` / `_resume_mounted_ids` dedup guards — this branch mounts nothing itself.

Deliberately not gated on `peer_id not in self._history_ids`: the owner persists the row *before* emitting the receipt, so a racing sync may already carry the id, yet the receipt is still the authoritative "a new row landed" beat the count has to advance for.

## Testing evidence

Implementer's run on this branch (`cbd38972b`):

| gate | command | result |
| --- | --- | --- |
| flake8 | `.venv/bin/python -m flake8 .` | clean |
| black | `uvx --from black==26.1.0 black --check .` | clean |
| isort | `uvx isort==5.13.2 --check-only .` | clean |
| pyright (touched file) | `.venv/bin/python -m pyright --pythonpath .venv/bin/python local_operator/session/remote.py` | 0 errors |
| new tests | `tests/unit/session/test_history_window.py::test_peer_row_received_while_hidden_advances_the_viewer_count` and `tests/unit/tui/test_sidebar_peer_receipt.py::test_peer_row_on_a_hidden_session_paints_on_the_first_reveal` | 2 passed; both FAIL without the fix |
| session unit | `.venv/bin/python -m pytest tests/unit/session -q` | 1940 passed |
| related TUI | `env -u NO_COLOR TERM=xterm-256color .venv/bin/python -m pytest tests/unit/tui/test_sidebar_peer_receipt.py tests/unit/tui/test_session_sidebar.py -q` | 61 passed |
| full `tests/unit/tui` | — | **timed out at 900s — not claimed as run** |

No version bump: `pyproject.toml` is untouched. Combined-release rule: PRs never carry a version bump; this one does not.

## Not addressed (deliberate)

- **Wake receipts (`WakeDeliveredEvent`)** remain a sibling gap — deferred. Same shape (settled event that never enters `_live_history`, so the first-reveal count never grows), different key (`(wake_id, occurrence)`). Not in this PR.

### CODE REVIEW

**Comment by damianvtran** [comment]
### QA report — round 1

**Verdict: PASS** on head `cbd38972b40a1ce16ffacb510329feac66d02872`

QA-tester, independent pass. Worktree `~/local-operator/.worktrees/peer-receipt-resume`. Python `~/local-operator/.venv/bin/python` with cwd = worktree (import resolved to the worktree source, not the parent checkout). Isolated `HOME` + `LOCAL_OPERATOR_CONFIG_DIR` under `/tmp/qa939-r1`. Every inherited `CMUX_*` unset (none were present). TUI runs used `env -u NO_COLOR TERM=xterm-256color`. Repo was not edited. Operator live sessions were not used (no test ids `home00`/`peer01`/`live00`/`peer-count` in `~/.local-operator/sessions`).

Matrix file: `/tmp/qa939-r1/matrix/qa-report-round-1.md`

| # | Surface | Result | Evidence |
| --- | --- | --- | --- |
| 1 | Hidden first-reveal TUI (`test_sidebar_peer_receipt.py`) | **PASS** | `test_peer_row_on_a_hidden_session_paints_on_the_first_reveal PASSED` |
| 2 | Hidden viewer count (`test_history_window.py::test_peer_row_received_while_hidden_advances_the_viewer_count`) | **PASS** | `PASSED`; together with #1: 2 passed in 4.38s |
| 3 | Invert both tests against `origin/main` (`831434f74`) | **PASS (repro)** | Throwaway worktree `/tmp/lo-qa939-main` (reclaimed). Confirmed `HAS_PEER_BRANCH False`. Count test: `AssertionError: the hidden viewer never filed the settled peer row`. TUI invert first hit a harness rename (`find_owner_record` vs `find_runtime_record` on main) — adapted **only the throwaway copy**, PR tree untouched — then the same assertion. Both fail without the fix. |
| 4 | Neighbours: reconnect_parity, peer_message, sidebar_live_tool_card, sidebar_repaint, session_sidebar | **PASS** (see Q-note) | 2 + 37 + 5 + 4 + 61 passed. One session_sidebar fail is **not this delta** (below). |
| 5 | Live-visible path does not double-paint | **PASS** | Unit: `test_live_peer_delivery_paints_a_cross_session_block`, `test_resume_replays_peer_message_without_double_paint`, `test_live_receipt_suppresses_its_replay`, `test_busy_steer_paints_one_peer_block_and_no_user_block` all PASSED. Assembled driver (real owner + socket): `peer_block_count=1`, text=`visible while current`. |
| 6 | `tests/e2e -m e2e -n0` | **BLOCKED** | No e2e file mentions `PeerMessageBlock` / `receive_peer_message`. This surface is the assembled unit TUI + driver, not the e2e stage. Full `tests/unit/tui` not run (prior 900s timeout). |
| 7 | `_remember_live` neighbour `test_sidebar_duration_replay.py` + whole `test_history_window.py` | **PASS** | 2 passed; 19 passed in 0.90s |

Assembled driver (real `RuntimeServer` owners, production `OperatorApp`, `save_capture` frames, looked at after rsvg-convert):

- Hidden **before** reveal (`/tmp/qa939-r1/shots/hidden-before-reveal.png`): parked on `home00`; `peer01` in the sidebar; no peer card.
- Hidden **first** reveal (`/tmp/qa939-r1/shots/hidden-first-reveal.png`): switch back to `peer01` paints exactly one inbound row `peer "peer-send design" · gates are green`. Driver: `filed_in_live_history=true`, `history_message_count=3`, `peer_block_count=1`.
- Live-visible (`/tmp/qa939-r1/shots/live-visible.png`): one inbound row `peer "peer-send live" · visible while current`, not two.

#### Q-findings

None against this delta.

**Q-note (not a finding on this PR):** `tests/unit/tui/test_session_sidebar.py::test_a_speculatively_leased_source_is_parked_and_stays_subscribed` failed twice on this worktree (`RuntimeError: Sidebar navigation requires an owner-backed session`). The same test **PASSES on current `origin/main`**. This PR does not touch `app.py` or that test file (diff is `remote.py` + two tests only). Cause is stale base: main now sets `remote.owns_runtime = False` and patches `find_runtime_record`; this branch's merge-base does not. Rebase would pick it up; it is not a regression of `cbd38972b`.

#### Gaps (not claimed)

- Full `tests/unit/tui` (timeout history).
- Full e2e stage — no peer-receipt surface there.
- Cold second-process `/resume` of a persisted peer row (covered indirectly by FakeSession replay + `display_history_window()`, not a second-process TUI boot).
- Wake receipts (`WakeDeliveredEvent`) — out of scope per PR, not exercised.

Did not merge. Did not edit the repo.

**Comment by damianvtran** [comment]
### Agent review — round 1
Reviewer: reviewer (xai/grok-4.6; provider fallback from anthropic/claude-opus-5 — Anthropic quota exhausted)
Scope: a3fd0716f..cbd38972b

Independent read of `git diff a3fd0716f..cbd38972b` (remote.py + `test_history_window.py` + `test_sidebar_peer_receipt.py`). Did not re-audit unchanged files.

## Verdict: **clean** (no BLOCKER, no MAJOR)

This round is **TERMINAL**. Remaining notes below are follow-ups, not a reason for another review round.

## What I checked

The bug is real and the mechanism matches the PR. A mailbox `PeerMessageDeliveredEvent` is a settled append with no `_MESSAGE_PHASE` lifecycle and no `event.message`, so the generic `_remember_live` path never claimed it. `history_generation` does not move on a plain append, so a parked sidebar source kept a frozen `history_message_count`. Reveal then:

1. accepted the cached presentation (`_sidebar_presentation_current` only rejects when `total < cached.history_size`), and
2. skipped the commit delta (`total > incoming.history_size`).

Hidden `_on_message` also drops `PeerMessageDelivered` without recording `_live_peer_receipts` (`_reduce_hidden_session_event` only tracks turn/compaction), so the live paint path cannot save it either.

Filing the persisted id into `_live_history` (and `_durable_seed_ids`) grows `history_message_count` by exactly one via the existing `durable + len(display_history_window()) - len(_history)` formula. Commit then projects `history[-(total - incoming.history_size):]`, and `project_settled_rows` mounts the `PeerMessageBlock` because `_live_peer_receipts` is empty for a hidden delivery. The branch mounts nothing itself.

Deliberately not gating on `_history_ids` is safe: if a racing sync already has the id, `display_history_window` overlays rather than appending (`key not in self._history_ids`), so the count cannot double.

Not gated on an empty `message_id` is the right skip — an id-less row cannot be counted once or deduped. Current senders always stamp `message.id`.

## Evidence (executed)

```
PYTHONPATH=. ~/local-operator/.venv/bin/python -m pytest \
  tests/unit/session/test_history_window.py::test_peer_row_received_while_hidden_advances_the_viewer_count \
  tests/unit/tui/test_sidebar_peer_receipt.py::test_peer_row_on_a_hidden_session_paints_on_the_first_reveal \
  -n0 -q
→ 2 passed in 4.56s

PYTHONPATH=. ~/local-operator/.venv/bin/python -m pytest \
  tests/unit/tui/test_peer_message.py tests/unit/session/test_history_window.py \
  -n0 -q
→ 56 passed in 7.94s

flake8 on the three changed files → clean
```

Both new tests are the right shape: real owner + viewer over the production socket; the TUI test is the operator repro (visit, hide, mailbox deliver, first reveal). I did not run the full unit matrix.

## Sibling: `WakeDeliveredEvent` — confirm MINOR, stay deferred

Same *shape* (settled event never enters `_live_history`), different *path*. An idle wake sets `streaming` and opens a turn, so `_sidebar_presentation_current` already cache-misses and rebuilds; a busy wake is already streaming. The leftover hole is reveal *after* the wake turn has ended, with no count bump — same second-reload symptom, much narrower than the idle mailbox peer case this PR fixes. Key is `(wake_id, occurrence)`, not a single `message_id`. Agree with prior MINOR and with leaving it out of this C2.

## Follow-ups (not blocking)

- **NIT-1** `remote.py:3504-3508` — the reconstructed `CustomMessage` omits `details["text"]` (the provenance envelope the owner persists). Harmless for TUI paint (`body` is what `PeerMessageBlock` reads). Only matters if a racing sync already has the id and `display_history_window` overlays this thinner row over the durable one. Not user-visible on the reveal path this PR ships.
- **NIT-2** `test_sidebar_peer_receipt.py:164-167` — docstring says the test asserts the count advanced *and* the block mounted; the body only asserts the block (the count lives in the sister unit test). Fine.

No other findings.

**Comment by damianvtran** [comment]
### QA report — round 2

**Verdict: FAIL** (one Q-finding, mechanical fix) — independent convergence pass on head `1a0dc30f3`, isolated config dir, no live sessions touched. Runner disclosure: executed by zai/glm-5.3 (fallback — primary model quota exhausted mid-session).

**Rebase equivalence pre-check:** PR commit patch is a pure rebase — the sorted +/- line sets of `cbd38972b^..cbd38972b` and `1a0dc30f3^..1a0dc30f3` are byte-identical (343 lines each; only hunk headers/context drift from upstream renames). Round-2 focus was therefore semantic conflicts against the moved base (#916/#922/#923/#929/#936, v0.54.5–0.54.7), and one exists.

| Surface | Result |
|---|---|
| `tests/unit/tui/test_sidebar_peer_receipt.py` (first-reveal paint, exactly one block) | **FAIL** — Q1 |
| `test_history_window.py::test_peer_row_received_while_hidden_advances_the_viewer_count` (+ full `test_viewer_protocol.py`, the protocol seam #929 touched) | PASS — 12 passed |
| `tests/unit/tui/test_reconnect_parity.py` (neighbouring surface main also moved) | PASS — 2 passed |
| #929 regression `tests/unit/tui/test_sidebar_live_tool_card.py` — resume double-paint, gated waiting rows, pending gate | PASS — 12 passed |
| `unanswered_tail_call_ids` still wired | PASS — defined `protocol.py:43`, consumed `remote.py:2642–2695` (pending gate) + `session.py:3537/3562`; pending-gate tests above pass |

**Q1 (blocker): the PR's only TUI-side test is dead on head.** `tests/unit/tui/test_sidebar_peer_receipt.py` collects exactly one test — the headline first-reveal assertion — and it errors in fixture setup:

```
$ env -u NO_COLOR -u CMUX_* TERM=xterm-256color LOCAL_OPERATOR_CONFIG_DIR=<isolated> \
    ~/local-operator/.venv/bin/python -m pytest tests/unit/tui/test_sidebar_peer_receipt.py -q
E   AttributeError: 'module' object at local_operator.mobile.attach_client has no attribute 'find_owner_record'
../../.venv/lib/python3.14/site-packages/_pytest/monkeypatch.py:97: AttributeError
FAILED tests/unit/tui/test_sidebar_peer_receipt.py::test_peer_row_on_a_hidden_session_paints_on_the_first_reveal
1 failed, 14 warnings in 2.10s
```

Cause: upstream #916 (43c1a35ac) renamed `find_owner_record` → `find_runtime_record` after the round-1 base; line 132 of the new test still patches the old name, so `monkeypatch.setattr` raises inside the `live_owners` fixture. The rename kept the signature — `(config_dir, session_id) -> tuple[SessionRecord | None, int | None]` — and the test's `find` fake is already compatible; every sibling test in the tree patches the new name (`test_sidebar_live_tool_card.py:202`, `test_sidebar_longrun.py:189`, `test_phone_startup.py:307`, `test_eager_runtime.py:490`, `test_remote_disconnect.py:589`). Remediation should be a one-line rename of the patch target, then re-run the file.

Notes: the production-side change itself is still proven on head — the session-side `test_peer_row_received_while_hidden_advances_the_viewer_count` passes on `1a0dc30f3` — but with the pilot test erroring there is no first-reveal visual/behavioural evidence on this head, which is why Q1 gates the round. Gaps: delta-focused per round-2 scope (full matrix not re-run; no e2e — not implicated by the delta).

Full matrix with commands and actual outputs: `/tmp/qa939/matrix_round2.md`. Not merging; repo untouched.

**Comment by damianvtran** [comment]
### Agent review — round 2
Reviewer: reviewer (zai/glm-5.3 — provider fallback mid-round from anthropic/claude-opus-5, anthropic quota exhausted; fallback disclosed per gate)
Scope: cbd38972b..1a0dc30f3

Convergence audit of the rebase onto origin/main c057b27a7 (#929 landed under us). Not a full re-audit; round 1 was CLEAN on cbd38972b.

**Content-unchanged proof**
- `git range-diff a3fd0716f..cbd38972b origin/main..HEAD` → single commit `!`, with hunks touching only import-context lines (main's parenthesized reformat of the `session.protocol` import; `test_history_window.py` import union from #929).
- Stronger check: full `-U0` +/- line multisets of the two commit versions are **byte-identical** (337 lines each, sorted `diff` empty). The `unanswered_tail_call_ids` union is context-only at `-U0`, so the commit's own lines carried over exactly. No version bump in the PR (3 files: remote.py + two test files). ✓

**Semantic-conflict checks in `local_operator/session/remote.py` at HEAD**
1. `_remember_live` `PeerMessageDeliveredEvent` branch intact (remote.py:3459–3507), including the id-less-sender skip and early `return`. ✓
2. `unanswered_tail_call_ids` imported (remote.py:98–102) **and** called (remote.py:2651, consumed at :2661/:2695) — no orphaned import. ✓
3. No clash with #929's live-tool-call resume path: the `ToolExecutionEndEvent` branch sits immediately above ours (remote.py:3450) as an independent `isinstance` check with disjoint id spaces (`live-tool:<id>` vs persisted peer ids); both #929 guard tests pass at HEAD. ✓

**Targeted run** (worktree's own venv; `local_operator.__file__` verified to resolve inside the worktree): `tests/unit/session/test_history_window.py`, `tests/unit/tui/test_sidebar_peer_receipt.py`, `tests/unit/tui/test_peer_message.py`, `tests/unit/tui/test_sidebar_live_tool_card.py`, `tests/unit/tui/test_sidebar_duration_replay.py` → **1 failed, 73 passed**. All non-blocker tests pass, including the peer-receipt count test (test_history_window.py:393) and both #929 live-tool guards.

**Findings**

- **BLOCKER 1 — rebase semantic conflict in the PR's own test.** `tests/unit/tui/test_sidebar_peer_receipt.py:132` patches `local_operator.mobile.attach_client.find_owner_record`, but #916 (43c1a35ac, in the rebase window) renamed that function to `find_runtime_record` (attach_client.py:671). `monkeypatch.setattr` defaults to `raising=True`, so this is a deterministic `AttributeError` at fixture setup — the file's sole test (`test_peer_row_on_a_hidden_session_paints_on_the_first_reveal`, the PR's flagship regression guard) fails at HEAD and the required unit CI is red; the PR cannot merge as-is. Production code is unaffected: the fake's shape `(config_dir, session_id) -> (record, pid)` already matches `find_runtime_record`'s signature, and the surrounding fixture lines (`OwnedSessionHandle`, `RuntimeServer`, `RemoteSession.connect`) all resolve at HEAD. Fix: one line — patch `find_runtime_record` instead (swept the commit's other 337 lines: every remaining `owner` token is prose or a local variable, no other renamed API is referenced).

**Verdict: NOT clean — 1 BLOCKER (test-only, one-line remediation).** The remote.py fix itself survived the rebase intact and conflict-free; the blocker is confined to the stale patch target. After the one-line fix, round 3 should be scoped to that single changed line.

**Comment by damianvtran** [comment]
### Agent review remediation — round 2

Head: `1a0dc30f3` → `fb474f18bc2869d4f763cbd91764a37b5ce49e90` (one commit, fast-forward push, no force; no version bump). This comment also answers the QA round-2 report — both streams' findings are the same single issue.

- **BLOCKER-1 / Q1 — FIXED in `fb474f18b`** (`fix(tui): patch find_runtime_record after owner→runtime rename`). One-line change at `tests/unit/tui/test_sidebar_peer_receipt.py:132`: the fixture now patches `local_operator.mobile.attach_client.find_runtime_record` (the post-#916 name, confirmed at `attach_client.py:671`) instead of the stale `find_owner_record`. The fake's shape was already correct and is untouched. Sweep of the file for `find_owner_record` / `owner_record` after the edit: zero matches; the source module itself has no `find_owner_record` left either.

**Evidence** — the exact commands from both reports, on new head `fb474f18b` in the worktree:

```
$ env -u NO_COLOR TERM=xterm-256color ~/local-operator/.venv/bin/python -m pytest \
    tests/unit/tui/test_sidebar_peer_receipt.py \
    tests/unit/session/test_history_window.py::test_peer_row_received_while_hidden_advances_the_viewer_count -q
2 passed, 12 warnings in 5.36s
```

The PR's flagship regression guard (`test_peer_row_on_a_hidden_session_paints_on_the_first_reveal`) now collects and passes at head, alongside the viewer-count test.

Nothing rejected, nothing deferred. Production code unchanged in this round; remote.py is untouched since the reviewed `1a0dc30f3`.

**Comment by damianvtran** [comment]
### Agent review — round 3
Reviewer: reviewer (zai/glm-5.3 — provider fallback from anthropic/claude-opus-5, anthropic credentials temporarily unavailable; fallback disclosed per gate)
Scope: 1a0dc30f3..fb474f18b

Scope discipline: this round audits only the remediation delta. `remote.py` was approved in round 1 on cbd38972b and confirmed intact through the rebase in round 2; it is not re-audited.

**Round 2 BLOCKER-1 (test-only: stale monkeypatch target) — fixed.** Verified:

- `git diff 1a0dc30f3..fb474f18b` is exactly the one stated line: `monkeypatch.setattr` target renamed `local_operator.mobile.attach_client.find_owner_record` → `...find_runtime_record` (tests/unit/tui/test_sidebar_peer_receipt.py:132). `git diff --name-only` confirms no other file changed, so production `session/remote.py` (including the `_remember_live` path) is byte-identical between the heads.
- No `find_owner_record` remains in any source file under `local_operator/` or `tests/`; the only grep hits are stale `__pycache__` `.pyc` artifacts, which regenerate on next compile.
- Fake signature matches the real one: fake `find(_directory: Path, session_id: str) -> tuple[Any, Any]` (test:115-117) vs `find_runtime_record(config_dir: Path, session_id: str) -> tuple[SessionRecord | None, int | None]` (attach_client.py:671-673) — same arity and parameter shapes, returns `(record, pid)` or `(None, None)` per the contract.
- The patch remains effective end to end: every production call site (session/remote.py:968, tui/app.py:4700, wakes/supervisor.py:128, …) imports `find_runtime_record` function-locally at call time, so the patched module attribute is what they bind.
- Execution proof: `env -u NO_COLOR TERM=xterm-256color .venv/bin/python -m pytest tests/unit/tui/test_sidebar_peer_receipt.py -q` → `1 passed, 10 warnings in 4.86s`. The warnings are pre-existing Pydantic V1-style `@validator` deprecations in `types.py`, unrelated to this diff.

Findings: none — no blocker, major, minor, or nit.

Verdict: **clean — TERMINAL.** The single round-2 blocker is resolved by the exact scoped one-line rename; production code is unchanged from the round-1-approved state. Remaining minors/nits from earlier rounds are follow-ups, not grounds for another round. No further agent-review round required on this PR.

**Comment by damianvtran** [comment]
### QA report — round 3

**QA:** qa-tester · model: `zai/glm-5.3` (provider fallback disclosed: Anthropic quota exhausted mid-session)
**Scope (delta):** `1a0dc30f3..fb474f18b` — test-fixture-only rename `find_owner_record` → `find_runtime_record` (+1/−1, one file; **no production code changed**)
**Head:** `fb474f18bc2869d4f763cbd91764a37b5ce49e90` — worktree clean, PR head OID matches, so this round is fresh on head.

**Verdict: PASS** — no Q-findings. Round-2 FAIL (Q1: fixture patched the pre-rename `find_owner_record`) is resolved: the fixture now patches `local_operator.mobile.attach_client.find_runtime_record` and the previously-failing test passes.

| # | Surface | Command | Actual output | Result |
|---|---------|---------|---------------|--------|
| 1 | TUI first-reveal peer receipt — `tests/unit/tui/test_sidebar_peer_receipt.py` (whole file, single test `test_peer_row_on_a_hidden_session_paints_on_the_first_reveal`) | `env -u NO_COLOR TERM=xterm-256color ~/local-operator/.venv/bin/python -m pytest tests/unit/tui/test_sidebar_peer_receipt.py -n0 -q` | `1 passed, 2 warnings in 3.78s` — asserts `len(blocks) == 1` ("expected exactly one peer receipt on the first reveal", i.e. exactly one `PeerMessageBlock`, no double-paint) and `blocks[0].text() == "gates are green"` | PASS |
| 2 | Count-signal — `tests/unit/session/test_history_window.py::test_peer_row_received_while_hidden_advances_the_viewer_count` | same env, `-n0 -q` | `1 passed, 2 warnings in 0.34s` | PASS |

Environment: worktree `~/local-operator/.worktrees/peer-receipt-resume`; every inherited `CMUX_*` variable unset before the run (verified 0 remaining); `NO_COLOR` unset, `TERM=xterm-256color`; serial `-n0`; config isolated via the test's own `tmp_path` config dir — no live sessions touched. Warnings are the pre-existing Pydantic V1 `@validator` deprecations in `local_operator/types.py`, present on main and unrelated to this PR.

Gaps: per round-3 scoping only the remediation delta was re-run; since the delta contains zero production-code change, rounds 1–2 coverage of the production behaviour stands as-is. No new gaps identified.

Matrix + raw pytest output: `/tmp/qa-939-r3/matrix.md`, `/tmp/qa-939-r3/test1-sidebar.out`, `/tmp/qa-939-r3/test2-count.out`.
